// IT SHOULD BE SYNCED WITH C# SHARED EVENTS

const events = {
  UI_LOADED: "UI_LOADED",
  UI_LOGIN_SHOW: "UI_LOGIN_SHOW",
  UI_LOGIN_SUBMIT: "UI_LOGIN_SUBMIT",
  UI_LOGIN_SUBMIT_OK: "UI_LOGIN_SUBMIT_OK",
  UI_LOGIN_SUBMIT_ERROR: "UI_LOGIN_SUBMIT_ERROR"
};

export { events };
