// IT SHOULD BE SYNCED WITH C# SHARED EVENTS

const events = {
  UI_LOADED: "UI_LOADED",

  UI_AUTH_SHOW: "UI_AUTH_SHOW",

  SERVER_LOGIN_SUBMIT: "SERVER_LOGIN_SUBMIT",
  SERVER_REGISTER_SUBMIT: "SERVER_REGISTER_SUBMIT",

  UI_LOGIN_CREDENTIALS_GET: "UI_LOGIN_CREDENTIALS_GET",
  UI_LOGIN_SHOW: "UI_LOGIN_SHOW",
  UI_LOGIN_SUBMIT_OK: "UI_LOGIN_SUBMIT_OK",
  UI_LOGIN_SUBMIT_ERROR: "UI_LOGIN_SUBMIT_ERROR",

  UI_REGISTER_SHOW: "UI_REGISTER_SHOW",
  UI_REGISTER_SUBMIT_OK: "UI_REGISTER_SUBMIT_OK",
  UI_REGISTER_SUBMIT_ERROR: "UI_REGISTER_SUBMIT_ERROR",

  UI_LOBBY_CREATE_CUSTOMIZE: "UI_LOBBY_CREATE_CUSTOMIZE"
};

export { events };
