// IT SHOULD BE SYNCED WITH C# SHARED EVENTS

const events = {
  UI_LOADED: "UI_LOADED",
  UI_LOGIN_SHOW: "UI_LOGIN_SHOW",
  UI_LOGIN_SUBMIT: "UI_LOGIN_SUBMIT",
  UI_LOGIN_OK: "UI_LOGIN_OK",
  UI_LOGIN_ERROR: "UI_LOGIN_ERROR",

  UI_REGISTER_SHOW: "UI_REGISTER_SHOW",
  UI_REGISTER_SUBMIT: "UI_REGISTER_SUBMIT",
  UI_REGISTER_OK: "UI_REGISTER_OK",
  UI_REGISTER_ERROR: "UI_REGISTER_ERROR"
};

export { events };
