// IT SHOULD BE SYNCED WITH C# SHARED EVENTS

export const UI_LOADED = "UI_LOADED";
export const UI_AUTH_SHOW = "UI_AUTH_SHOW";
export const SERVER_LOGIN_SUBMIT = "SERVER_LOGIN_SUBMIT";
export const SERVER_REGISTER_SUBMIT = "SERVER_REGISTER_SUBMIT";
export const UI_LOGIN_CREDENTIALS_GET = "UI_LOGIN_CREDENTIALS_GET";
export const UI_LOGIN_SHOW = "UI_LOGIN_SHOW";
export const UI_LOGIN_SUBMIT_OK = "UI_LOGIN_SUBMIT_OK";
export const UI_LOGIN_SUBMIT_ERROR = "UI_LOGIN_SUBMIT_ERROR";
export const UI_REGISTER_SHOW = "UI_REGISTER_SHOW";
export const UI_REGISTER_SUBMIT_OK = "UI_REGISTER_SUBMIT_OK";
export const UI_REGISTER_SUBMIT_ERROR = "UI_REGISTER_SUBMIT_ERROR";
export const UI_LOBBY_CREATOR_CUSTOMIZE = "UI_LOBBY_CREATOR_CUSTOMIZE";
export const UI_LOBBY_CREATOR_RESET = "UI_LOBBY_CREATOR_RESET";
export const UI_LOBBY_CREATOR_SHOW = "UI_LOBBY_CREATOR_SHOW";
export const UI_LOBBY_CREATOR_INIT = "UI_LOBBY_CREATOR_INIT";
export const UI_LOBBY_CREATOR_INIT_OK = "UI_LOBBY_CREATOR_INIT_OK";
export const LOBBY_CREATOR_SUBMIT = "LOBBY_CREATOR_SUBMIT";
