// IT SHOULD BE SYNCED WITH C# SHARED EVENTS

export const UI_LOADED = "UI_LOADED";
export const AUTH_SHOW = "AUTH_SHOW";

export const LOGIN_CREDENTIALS_GET = "LOGIN_CREDENTIALS_GET";
export const LOGIN_SHOW = "LOGIN_SHOW";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";
export const LOGIN_SUBMIT_OK = "LOGIN_SUBMIT_OK";
export const LOGIN_SUBMIT_ERROR = "LOGIN_SUBMIT_ERROR";

export const REGISTER_SHOW = "REGISTER_SHOW";
export const REGISTER_SUBMIT = "REGISTER_SUBMIT";
export const REGISTER_SUBMIT_OK = "REGISTER_SUBMIT_OK";
export const REGISTER_SUBMIT_ERROR = "REGISTER_SUBMIT_ERROR";

export const LOBBY_CREATOR_SHOW = "LOBBY_CREATOR_SHOW";
export const LOBBY_CREATOR_INIT = "LOBBY_CREATOR_INIT";
export const LOBBY_CREATOR_INIT_OK = "LOBBY_CREATOR_INIT_OK";
export const LOBBY_CREATOR_CUSTOMIZE = "LOBBY_CREATOR_CUSTOMIZE";
export const LOBBY_CREATOR_SUBMIT = "LOBBY_CREATOR_SUBMIT";
export const LOBBY_CREATOR_SUBMIT_OK = "LOBBY_CREATOR_SUBMIT_OK";
export const LOBBY_CREATOR_CANCEL = "LOBBY_CREATOR_CANCEL";

export const LOBBY_SELECTOR_SHOW = "LOBBY_SELECTOR_SHOW";
